vint:
  config_path: "/home/airlab/seg_test4/vint-segmentation-funetuning/train/config/segmentation_vint.yaml"
  ckpt_path: "/home/airlab/seg_test4/vint-segmentation-funetuning/deployment/model_weights/best.pth"

segmentation_vint:
  config_path: "/home/airlab/seg_test4/vint-segmentation-funetuning/train/config/segmentation_vint.yaml"
  ckpt_path: "/home/airlab/seg_test4/vint-segmentation-funetuning/deployment/model_weights/best.pth"

late_fusion:
  config_path: "../../train/config/late_fusion.yaml"
  ckpt_path: "../model_weights/vint_late_fusion.pth"

gnm:
  config_path: "../../train/config/gnm.yaml"
  ckpt_path: "../model_weights/gnm_large.pth"

nomad:
  config_path: "/home/joonyeol/nomad_ws/src/visualnav-transformer/train/config/nomad.yaml"
  ckpt_path: "/home/joonyeol/nomad_ws/src/visualnav-transformer/deployment/model_weights/nomad.pth"
# add your own model configs here after saving the *.pth file to ../model_weight
