# Segmentation ViNT Configuration
project_name: "segmentation_vint"
run_name: "seg_vint_fuse_scand"
use_wandb: false

seed: 42  # For reproducibility

# ==================================================================
# Model Parameters
# ==================================================================
model_type: "segmentation_vint"
obs_encoder: "resnet34"
obs_encoding_size: 512
context_size: 5
len_traj_pred: 8
learn_angle: false

# --- Co-Pilot Specific ---
num_seg_classes: 5  # SCAND: floor, wall, door, furniture, unknown
seg_model_name: "scand"  # Must match dataset class mapping
seg_feature_dim: 256 # Dimensionality of the feature from the seg_encoder

# --- Pass-through arguments for the core ViNT model's decoder ---
model_params:
  mha_num_attention_heads: 8
  mha_num_attention_layers: 4
  mha_ff_dim_factor: 4

# ==================================================================
# Training Parameters
# ==================================================================
epochs: 50 # Total training epochs
lr: 5e-5

# Two-stage training schedule
stage1_epochs: 25 # Stage 1: Train co-pilot modules with ViNT frozen
stage2_epochs: 25 # Stage 2: Fine-tune the entire model

batch_size: 8
eval_batch_size: 64
gradient_accumulation_steps: 2

# Optimizer settings
optimizer: "adamw"
scheduler: "cosine"

# ==================================================================
# Loss Parameters (for CoPilotNavigationLoss)
# ==================================================================
action_loss_weight: 1.0
dist_loss_weight: 0.5
# <<< ADDED: Crucial parameter for the co-pilot model >>>
consistency_weight: 0.2

# ==================================================================
# Metric Parameters (for NavigationMetrics)
# ==================================================================
success_threshold: 0.3 # Max distance from goal (in normalized coords) to be a success
collision_margin: 5    # Pixel radius around a trajectory point to check for obstacles

# ==================================================================
# Data Parameters
# ==================================================================
image_size: [128, 160]
num_workers: 8

# Distance & Action sampling parameters
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 1
  max_dist_cat: 10

# ==================================================================
# Datasets
# ==================================================================
datasets:
  scand:
    data_folder: "/home/airlab/seg_test4/vint-segmentation-funetuning/datasets/scand_processed"
    # This folder of pre-computed masks is mandatory for this model
    seg_data_folder: "/home/airlab/seg_test4/vint-segmentation-funetuning/datasets/scand_seg"
    train: "/home/airlab/seg_test4/vint-segmentation-funetuning/train/vint_train/data/data_splits/scand/train"
    test: "/home/airlab/seg_test4/vint-segmentation-funetuning/train/vint_train/data/data_splits/scand/test"
    waypoint_spacing: 1
    negative_mining: true

# ==================================================================
# Pretrained Model
# ==================================================================
pretrained_vint_path: "/home/airlab/seg_test4/vint-segmentation-funetuning/deployment/model_weights/vint_original.pth"

# ==================================================================
# Logging
# ==================================================================
print_log_freq: 50
eval_freq: 5 # Evaluate and visualize every 5 epochs
