# Segmentation ViNT Configuration
project_name: "segmentation_vint"
run_name: "seg_vint_fuse_scand"
use_wandb: true

model_type: "segmentation_vint"

# ==================================================================
# Model Parameters
# ==================================================================
obs_encoder: "resnet34"
obs_encoding_size: 512
context_size: 5
len_traj_pred: 8
learn_angle: false
late_fusion: true
mha_num_attention_heads: 8
mha_num_attention_layers: 4
mha_ff_dim_factor: 4

vint_feature_channels: 512

# ==================================================================
# Segmentation Specific
# ==================================================================
num_seg_classes: 5  # SCAND: floor, wall, door, furniture, unknown
seg_model_name: "scand"  # Must match dataset class mapping
seg_model_type: "unet"
seg_encoder: "resnet34"
fusion_type: "gated"  # or "simple" for baseline
use_semantic_goals: true

# CRITICAL for heuristics:
use_pseudo_labels: false
# pseudo_label_model: null  # NULL means use heuristics, not pretrained model

# ==================================================================
# Training Parameters
# ==================================================================
epochs: 60
lr: 5e-5

# FuSe schedule epochs
stage1_epochs: 20 # Frozen ViNT
stage2_epochs: 40  # Unfrozen ViNT with lower LR
# Stage 3 uses remaining epochs (80 - 30 - 40 = 10)

batch_size: 16
eval_batch_size: 64
gradient_accumulation_steps: 2

# Optimizer settings
optimizer: "adamw"
scheduler: "cosine"
warmup: false
warmup_epochs: 0

# Gradient clipping
clipping: true  # ADD THIS
max_norm: 1.0  # ADD THIS

# ==================================================================
# Loss Parameters
# ==================================================================
# These are used if uncertainty weighting is disabled
action_loss_weight: 1.5
dist_loss_weight: 0.1
seg_loss_weight: 0.3

# ==================================================================
# Data Parameters
# ==================================================================
image_size: [128, 160]
normalize: true
goal_type: "image"
num_workers: 8
eval_fraction: 0.25

# Distance parameters
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 1
  max_dist_cat: 10

# ==================================================================
# Datasets
# ==================================================================
datasets:
  scand:
    data_folder: "/home/airlab/vint_fuse3/datasets/scand_processed"
    seg_data_folder: "/home/airlab/vint_fuse3/datasets/scand_seg"
    train: "/home/airlab/vint_fuse3/train/vint_train/data/data_splits/scand/train"
    test: "/home/airlab/vint_fuse3/train/vint_train/data/data_splits/scand/test"
    waypoint_spacing: 1
    negative_mining: true
    goals_per_obs: 1
    end_slack: 0

# ==================================================================
# Pretrained Model
# ==================================================================
pretrained_vint_path: "/home/airlab/vint_fuse3/deployment/model_weights/vint_original.pth"

# ==================================================================
# Logging
# ==================================================================
print_log_freq: 50
image_log_freq: 500
num_images_log: 8 
visualization_freq: 10

# ==================================================================
# Project Settings (ADD THIS SECTION)
# ==================================================================
project_folder: null  # Will be set automatically by train script
seed: 42  # For reproducibility